services:
  db:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_PASSWORD: password
    ports:
      - 3000:3000
    volumes:
      - .:/OriginalPortfolio
volumes:
  db-data: